### ISSUE TITLE
empty arrays not handled correctly 

### ISSUE THREAD

**Issue by ssmogos** [rxi/json.lua#11]
Parsing JSON with empty arrays does not work. 
Example:
local json = loadfile("json.lua")()

d = json.decode("{\"tags\":[]}")
local fmt = string.format

 print( fmt("[test] %s ", d.tags) )

**Comment by rxi** [comment]
This works as expected for me, with corrections to your example:

```lua
local json = loadfile("json.lua")()
local d = json.decode('{"tags":[]}')
print( string.format("[test] %s len:%d", tostring(d.tags), #d.tags) )
```

I get the output:

```
[test] table: 0x99a76e0 len:0
```

**Comment by ssmogos** [comment]
got this error before:
