### ISSUE TITLE
Floating point numbers with dot causing error

### ISSUE THREAD

**Issue by maciejmiklas** [rxi/json.lua#16]
Parsing such document

`    {
      "dt": 1548784800,
      "main": {
        "temp": -2.05,
        "temp_min": -2.18,
        "temp_max": -2.05,
        "pressure": 998.5,
        "sea_level": 1019.79,
        "grnd_level": 998.5,
        "humidity": 89,
        "temp_kf": 0.12
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 36
      },
      "wind": {
        "speed": 1.56,
        "deg": 233.002
      },
      "rain": {},
      "snow": {
        "3h": 0.004
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2019-01-29 18:00:00"
    }`

gives an error: 
invalid number '-2.05' at line 4 col 17

**Comment by rxi** [comment]
I tried running the provided string through the library using LuaJIT, 5.1 and 5.3 — in all cases it read without error. Does the exact input you provided above result in the error? If not can you provide the original file which does.

Internally `json.lua` uses the `tonumber()` function, it might also be helpful to check if `tonumber("-2.05")` works as expected in your lua version, preferably immediately before the failing call to `json.decode()`.

**Comment by maciejmiklas** [comment]
I've been using EclipseLua with build in Lua, executing from command line works fine, so there must me something wrong with my installation. Thank you!
