### ISSUE TITLE
Missing decode bench for json4lua

### ISSUE THREAD

**Issue by josefnpat** [rxi/json.lua#2]
For some reason json4lua's decode is commented out on bench_decode:

https://github.com/rxi/json.lua/blob/master/bench/bench_decode.lua#L8

When I uncomment it out, it locks up.

What's going on?

**Comment by rxi** [comment]
Unfortunately json4lua's decoding takes so much longer on non-tiny input than all the others that I had to omit it. The locking up is json4lua at work, if you give it a few minutes (or more) it should eventually finish.

**Comment by josefnpat** [comment]
Ok, thanks
