### ISSUE TITLE
decoding of object with 'duplicate' key

### ISSUE THREAD

**Issue by odanoburu** [rxi/json.lua#32]
in lua:

```lua
> dump( json.decode("{1: 1, '1':2}"))
{ [1] = 1,["1"] = 2,} 
```

whereas in javacript we have:
```
> Object.entries({1: 1, '1':2}).length
1
```

so in lua we should probably have:

```lua
> dump( json.decode("{1: 1, '1':2}"))
{["1"] = 2,} 
```

**Comment by xphip** [comment]
```output
[error] 30#30: *4 lua entry thread aborted: runtime error: json.lua:185: expected string for key
```
The string (`{1: 1, '1':2}`) you are trying to parse isn't a valid JSON.
Index cannot be numeric type. Cannot have duplicate index. Double quotes to define an index.

> Trying to encode values which are unrepresentable in JSON will never result in type conversion or other magic: sparse arrays, tables with mixed key types or invalid numbers (NaN, -inf, inf) will raise an error
[https://github.com/rxi/json.lua#notes](https://github.com/rxi/json.lua#notes)

---

In Javascript, [Object.entries](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) isn't a JSON parser.
> The Object.entries() method returns an array of a given object's own enumerable string-keyed property [key, value] pairs. 

The proper method to parse a JSON in Javascript is [JSON.parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse)
And trying to parse your string is returned:
```console
Uncaught SyntaxError: Unexpected number in JSON at position 1
```
---
Making these small corrections (even still with duplicate index) the code works fine.
```lua
local decoded = json.decode('{"1":1,"1":2}')
local encoded = json.encode(decoded)
ngx.say(encoded)

-- Output: {"1":2}
```

**Comment by odanoburu** [comment]
Thanks for the clarifications; no idea what I was thinking at the time.
