### ISSUE TITLE
json encode error

### ISSUE THREAD

**Issue by ffbh123456** [rxi/json.lua#35]

**Comment by ffbh123456** [comment]
```lua
json.encode({
        { { [1] = 1 }, { [2] = 100 } }
})
```
it will throw error

**Comment by rxi** [comment]
```lua
{ [2] = 100 }
```

> Trying to encode values which are unrepresentable in JSON will never result in type conversion or other magic: sparse arrays, tables with mixed key types or invalid numbers (NaN, -inf, inf) will raise an error
