### ISSUE TITLE
Invalid number like '0123' or '1.' should not be decoded without raising errors

### ISSUE THREAD

**Issue by lytinker** [rxi/json.lua#5]
Strings like '0123' or '1.' are invalid as described in ECMA-404 and can not be parsed to numbers. However, the function `tonumber()` regards such strings convertible to numbers. 

So the following code:
```
json.decode('1.')
```
will return the value 1 without any errors, which go against the JSON standard.

**Comment by FSMaxB** [comment]
Hm, at first I thought this could be easily implemented using lua pattern, but this isn't possible because there are no regex-style alternatives (`|`).

This makes it significantly more complicated!

**Comment by rxi** [comment]
The library aims to parse all *valid* JSON correctly, if it fails to do this it is a bug and should be fixed. In the case of certain invalid input I don't see any harm in allowing things such as non-standard-compliant numbers to parse, for example the ones you listed, in addition to hexadecimal literals (`0x123`).

Keep in mind that adding extra error checking for something like this adds a cost of code complexity and runtime overhead, which even if minute, offers very little, if any real benefit.

In the case of invalid input such as an unclosed object, missing comma or a stray colon, an error is raised as these would likely be the result of a human editing mistake or some other problem between the JSON being created and it being passed to the library.
