### ISSUE TITLE
Please add recursion / unlimited depth support

### ISSUE THREAD

**Issue by JurekRaben** [rxi/json.lua#8]
Currently the lib does not seem to support nested tables a.k.a. unlimited depth, e.g.
```lua
luaTable = { innerTable = { value1 = "value", value2 = "value" }, value1 = "value }
```
won't be supported currently. So I would like to request to support any kind of nested structure by using recursion.

**Comment by rxi** [comment]
I'm not sure I understand — the library handles the table in your example without issue, assuming we fix the unclosed string to make it valid lua:

```
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> json = require("json")
> luaTable = { innerTable = { value1 = "value", value2 = "value" }, value1 = "value" }
> =json.encode(luaTable)
{"innerTable":{"value2":"value","value1":"value"},"value1":"value"}
> 
```

**Comment by rxi** [comment]
Not infinite, but well beyond a reasonable amount.
